language: node_js
node_js:
  - "6"
before_script:
  - npm install hexo-cli -g
  - 
script:
  - hexo generate

deploy:
  provider: pages
  local_dir: public
  repo: https://github.com/MarxJiao/marxjiao.github.io.git
  skip_cleanup: true
  github_token: $GIT
  on:
    branch: master
